name: another_text_editing_controller
description: An alternative TextEditingController for using with language that need composing
version: 0.0.1
author: Panu Avakul
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter